HEADERS= br/br_cmd.c clock.cpp conf_file.cpp debug.cpp debug_menu.cpp dnc/dnc.cpp dnc/dnc_menu.cpp x10dev.cpp
OBJECTS= br_cmd.o clock.o conf_file.o debug.o debug_menu.o dnc.o dnc_menu.o x10dev.o

default: garden_debug

garden_debug: $(HEADERS)
	g++ $(HEADERS) -o garden_debug -lmenu -lncurses -std=c++11

clean:
	-rm -f *.o
	-rm -f garden_debug

